## XGBoost Classifier

In [14]:
import numpy as np
import pandas as pd

In [15]:
#using unscaled data
df_xgb = pd.read_csv("df_knn.csv")

In [16]:
df_xgb.head()

market  funding_total_usd  region  city  funding_rounds  Founding_year  \
0     226            1750000     104   449               1           2012   
1     309            7000000      51   469               1           2011   
2      79            2535000     131   569               2           2010   
3       8            1250000     131   569               2           2011   
4      79              50000      32   145               1           2009   

   first_funding_year  last_funding_year  first_funding_gap  last_funding_gap  \
0                2012               2012                  0                 0   
1                2013               2013                  2                 2   
2                2010               2011                  0                 1   
3                2011               2011                  0                 0   
4                2009               2009                  0                 0   

   first_last_funding_gap  success  
0                       0        1  
1                       0        0  
2                       1        1  
3                       0        1  
4                       0        0

In [17]:
from sklearn.model_selection import train_test_split
x = df_xgb.drop('success', axis = 1)
y = df_xgb['success']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [18]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [19]:
y_pred = model.predict(x_test)

In [21]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.64      0.57      0.60       576
           1       0.72      0.77      0.74       804

    accuracy                           0.69      1380
   macro avg       0.68      0.67      0.67      1380
weighted avg       0.69      0.69      0.69      1380

[[329 247]
 [183 621]]


In [22]:
from sklearn import metrics
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))

ACCURACY OF THE MODEL:  0.6884057971014492


## Scaling Features/Data

In [23]:
#using scaled features
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(x_train)
X_test_scaled = sc.transform(x_test)

In [33]:
X_train_scaled

array([[ 0.19076317, -0.19834886, -1.25531221, ...,  2.20552423,
         2.40743888,  0.86067697],
       [-1.53383714, -0.26149105,  0.14212758, ..., -0.0824495 ,
        -0.25466328, -0.56253493],
       [ 1.12567807, -0.30423346, -1.49549718, ..., -0.43444546,
        -0.42104466, -0.08813096],
       ...,
       [ 1.24367704, -0.33191888, -0.40374734, ..., -0.25844748,
        -0.42104466, -0.56253493],
       [-1.34322342, -0.0409791 , -0.14172738, ..., -0.43444546,
        -0.58742605, -0.56253493],
       [-0.56261486, -0.31977615,  0.7316725 , ..., -0.43444546,
        -0.58742605, -0.56253493]])

In [25]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train_scaled, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [27]:
y_pred_scaled = model.predict(X_test_scaled)

In [29]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(classification_report(y_test, y_pred_scaled))
print(confusion_matrix(y_test, y_pred_scaled))

              precision    recall  f1-score   support

           0       0.64      0.57      0.60       576
           1       0.72      0.77      0.74       804

    accuracy                           0.69      1380
   macro avg       0.68      0.67      0.67      1380
weighted avg       0.69      0.69      0.69      1380

[[329 247]
 [183 621]]


In [30]:
from sklearn import metrics
print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred_scaled))
#similar accuracy obtained for both scaled and unscaled data

ACCURACY OF THE MODEL:  0.6884057971014492
